### PR TITLE
change dependency and add dev requirements file

### PR DESCRIPTION
**Pull request by RemiDesgrange**
Right now, some dependencies are not used, like logging which is in the python std library.

I also add `requirements-dev.txt` for ease of dev.

I changed `lazyxml` to `xmltodict` because it's not well packaged and lazyxml cannot be `pip install` easily.

for robustness add `argparse` instead of manual argument parsing. I'm considering rewriting JSON/XML and status as Enum for robustness too, but I don't what are python plateform are targeted.

test are not passing right now, consider this PR as WIP, I'll fix text and squash ASAP

### CODE REVIEW

**Comment by sid5432** [comment]
Sounds good. Thanks for the enhancement and fixes! I'll be busy with work for the next few weeks, so I might not get to it right away, but let me know when the tests pass.

**Comment by RemiDesgrange** [comment]
Ok, it's a problem with time. I think time repr. 

```
E         -    ('date/time', 'Sat Jun 17 06:01:11 2006 (1150538471 sec)'),
E         ?                              ^^
E         +    ('date/time', 'Sat Jun 17 12:01:11 2006 (1150538471 sec)'),
E         ?
```

I have not idea how to deal with that but I will check on that. Maybe in a new pull request i'll look into making the date more "international" like `17/06/06 12:01:11` or maybe just timestamp :-)

**Comment by RemiDesgrange** [comment]
@sid5432 fiendly up :-) I'd like to have this merge before thinking about migration to python 3.

**Comment by sid5432** [comment]
I just merged your changes. It looks like it broke all sorts of things :-( I'm kind of busy right now, so I'm not sure when I'll be able to get to it. Sorry.

**Comment by RemiDesgrange** [comment]
I'm going to fix it :-)

**Pull request merged**
